### ISSUE TITLE
Update first few pages

### ISSUE THREAD

**Issue by tyronen** [liaohuqiu/fresco-docs-cn#18]
The Chinese sequence of pages has gotten out of date:
- The content now in index.html needs to be moved to getting-started.html.
- The content now in download-fresco.html needs to go to index.html. This needs to be the first page users visit after clicking the "Get Started" button.

In addition, the download-fresco.html page is still saying that Eclipse users is not supported. It is now. Please bring this up to date with the English page. We are still getting questions from users who think they have to build from source because they are using Eclipse.

I also notice there is an additional page, compile-in-android-studio.html. It looks like it is directing users to use Apricot. Can you send me an English translation of this page? 

Thanks again for your help in doing this awesome translation!

**Comment by liaohuqiu** [comment]
OK. Will be done soon.

**Comment by liaohuqiu** [comment]
Hi, @tyronen:

In china mainland, a big problem while compiling a Android Studio project it (all projects, not only fresco), is that, without a network proxy or VPN, we can not access jcenter.com, sometimes even github.com.  

This page `compile-in-android-studio.html` introduces the way about how to use the free network proxy [Red Apricot](http://honx.in/_VHRiboIaAxADyQus) while compiling project.

Do you really think you need a english version? If yes, I will send it to you tonight.

**Comment by liaohuqiu** [comment]
HI, @tyronen .

**Comment by liaohuqiu** [comment]
Since you have not reply this issue, so I close it first. Any question you can reopen it. 

Thanks. :)
