### ISSUE TITLE
Incorrect translation?

### ISSUE THREAD

**Issue by tyronen** [liaohuqiu/fresco-docs-cn#22]
https://github.com/facebook/fresco/issues/331 - comment at the bottom says there is an error in the Chinese translation.

**Comment by liaohuqiu** [comment]
Yes, it's taken from the first initial commit. Will be fixed soon. 

https://github.com/facebook/fresco/blob/05bd7dcc6c4e4629f510f8bf46aa45de68e7db7a/docs/03-using-other-network-layers.md

**Comment by liaohuqiu** [comment]
Fixed now. I will check all the document for keeping update, see #23 .
