### ISSUE TITLE
Update getting-started.html

### ISSUE THREAD

**Issue by tyronen** [liaohuqiu/fresco-docs-cn#24]
getting-started.html has some text in English that seems missing in Chinese.

Specifically this English text:

For images from the network, you will need to to request Internet permission from your users. Add this line to your AndroidManifest.xml file:

```
<uses-permission android:name="android.permission.INTERNET"/>
```

Near your application startup, before your app calls `setContentView()`, initialize the Fresco class:

```
Fresco.initialize(context);
```

At least one issue may have been filed by someone who initialized in the wrong place.

**Comment by liaohuqiu** [comment]
Well, sorry for that, I will fix it tomorrow. [UTC+8], and what about this issue: https://github.com/liaohuqiu/fresco-docs-cn/issues/18 ?
