### ISSUE TITLE
A markdown link-tag error

### ISSUE THREAD

**Issue by R1NC** [liaohuqiu/fresco-docs-cn#3]
In [02-datasources-datasubscribers.md](https://github.com/liaohuqiu/fresco-docs-cn/blob/docs/docs/02-datasources-datasubscribers.md),
`(closeable references)[closeable-references.html)`
should be:
`[closeable references](closeable-references.html)`

**Comment by liaohuqiu** [comment]
Fixed now. Thank your for you feedback.
