### ISSUE TITLE
你中文的Fresco文档已经 有些过时了

### ISSUE THREAD

**Issue by VVZ1991** [liaohuqiu/fresco-docs-cn#49]
Using the Image Pipeline Directly 里面的Api 都需要传Context啦，还有dataSource.subscribe();的方法 参数也变了

**Comment by liaohuqiu** [comment]
嗯，我需要重新过一遍，谢谢你的提醒。

**Comment by TacticalTwerking** [comment]
http://fresco-cn.org/docs/caching.html
1. Bitmap缓存
   [后处理] 链接挂了 (404)

**Comment by liaohuqiu** [comment]
Thanks to @desmond1121 . It's done now.
