### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tyronen** [liaohuqiu/fresco-docs-cn#5]
First of all, thank you so much for doing this!!

One request - can you add a license footer? You can copy or translate what we have in _includes/footer.html and docs/sample-license.md.

**Comment by liaohuqiu** [comment]
Sure. I'm just on it.

**Comment by liaohuqiu** [comment]
I've added the license footer. 

I've no idea should I keep the copyright line or not. I think it's better to keep it there. 

If there is anything I should do. Please feel free to let me know. Thank you for your help.
