### ISSUE TITLE
05-multiple-apks.md 存在错误

### ISSUE THREAD

**Issue by LeerGo** [liaohuqiu/fresco-docs-cn#60]
```
   文中第12行末尾处：“2011年15月以后的生产的大部分Android设备都使用它。”，2011年15月，这里请作者勘误一下 
   很棒的文档 谢谢 ;-) 👍
```

**Comment by diql** [comment]
我也发现了同样的问题，"Version 7 or higher of the ARM processor. Most Android phones released from 2011-15 are using this."这是原文，表示看的有点糊涂。

**Comment by LeerGo** [comment]
应该是“2011-15 年度发布的手机大多数都是用它”
